MvcMovie/Models/ErrorViewModel.cs
using System;

namespace MvcMovie.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcMovie/Models/Movie.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MvcMovie.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }

        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }
}

MvcMovie/Controllers/CovidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcMovie.DataAccess;
using MvcMovie.ViewModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MvcMovie.Controllers
{
    public class CovidController : Controller
    {
        CovidDataAccess CovidDataAccess = new CovidDataAccess();
        // GET: /<controller>/

        public async Task<IActionResult> Index()
        {
            
            CovidViewModel covid = await CovidDataAccess.CovidService();
            List<CovidViewModel> covidList = await CovidDataAccess.CovidServiceLog();
           ViewData["covid"] = covid;
            ViewData["covidList"] = covidList;
            return View();
        }

    }
}

MvcMovie/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcMovie/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovie.Data;
using MvcMovie.Models;
using MvcMovie.ViewModel;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using MvcMovie.DataAccess;

namespace MvcMovie.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MvcMovieContext db;

        private readonly IHttpClientFactory _clientFactory;
        CovidDataAccess CovidDataAccess1 = new CovidDataAccess();

        public MoviesController(MvcMovieContext context)
        {
            db = context;
            

        }

        // GET: Movies
        [HttpGet]
        public  IActionResult  Index(string titleName)
        {
            List<Movie> moviesList =  db.Movie.ToList();
            if (!string.IsNullOrWhiteSpace(titleName)) {
                moviesList = moviesList.Where(x => x.Title.Contains(titleName)).ToList();
            }
         
            return   View(moviesList);
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await db.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseDate,Genre,Price")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Add(movie);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await db.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Price")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(movie);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await db.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await db.Movie.FindAsync(id);
            db.Movie.Remove(movie);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return db.Movie.Any(e => e.Id == id);
        }



    }
}

MvcMovie/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcMovie.Data;
using MvcMovie.Models;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MvcMovie.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : ControllerBase
    {
        private readonly MvcMovieContext db;
        // GET: api/values
        public ValuesController(MvcMovieContext context)
        {
            db = context;


        }
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Movie>>> Get()
        {
            return await db.Movie.ToListAsync();
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public async Task<Movie> Get(int id)
        {
            var todoItem = await db.Movie.FindAsync(id);

            if (todoItem == null)
            {
                //return NotFound();
                return null;
            }

            return todoItem;
        }
            // POST api/values
            [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

MvcMovie/Views/Covid/Index.cshtml
@model IEnumerable<MvcMovie.ViewModel.CovidViewModel>


@{
    ViewData["Title"] = "Home Page";
    var covid = ViewData["covid"] as MvcMovie.ViewModel.CovidViewModel;
    var covidList = ViewData["covidList"] as List<MvcMovie.ViewModel.CovidViewModel>;
}


<h2 class="display-4 text-center mt-5 mb-3">Covid Today</h2>
<div class="row text-center">
    <div class="col-md-3 mb-3">
        <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
            <div class="card-header">ติดเชื้อสะสม</div>
            <div class="card-body">
                <h1>@covid.Confirmed</h1> <br>
                <p>[ เพิ่มขึ้น @covid.NewConfirmed ]</p>
            </div>
        </div>

    </div>

    <div class="col-md-3 mb-3">
        <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
            <div class="card-header">หายแล้ว</div>
            <div class="card-body">
                <h1>@covid.Recovered</h1><br>
                <p>[เพิ่มขึ้น @covid.NewRecovered ]</p>
            </div>
        </div>
    </div>

    <div class="col-md-3 mb-3">
        <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
            <div class="card-header">รักษาอยู่ในโรงพยาบาล</div>
            <div class="card-body">
                <h1>@covid.Hospitalized</h1><br>
                <p> [ เพิ่มขึ้น @covid.NewHospitalized]</p>
            </div>
        </div>
    </div>
    <div class="col-md-3 mb-3">
        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
            <div class="card-header">เสียชีวิต</div>
            <div class="card-body">
                <h1>@covid.Deaths</h1><br>
                <p> [ เพิ่มขึ้น @covid.NewDeaths]</p>
            </div>
        </div>
    </div>
</div>

<table id="table_id" class="table" style="width:100%">
    <thead>

    </thead>
    <thead class="table-info">
        <tr>
            <th>
                ข้อมูลวันที่
            </th>
            <th>
                ติดเชื้อสะสม
            </th>
            <th>
                หายแล้ว
            </th>
            <th>
                รักษาอยู่ใน รพ.
            </th>
            <th>
                เสียชีวิต
            </th>
        </tr>



    </thead>
    <tbody>
        @foreach (var item in covidList)
        {
            <tr>
                <td>
                    @item.Date
                </td>
                <td>
                    @item.Confirmed
                </td>
                <td>
                    @item.Recovered
                </td>
                <td>
                    @item.Hospitalized
                </td>
                <td>
                    @item.Deaths
                </td>
            </tr>
        }
    </tbody>
</table>


@section Scripts
{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

MvcMovie/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcMovie/Views/Movies/Create.cshtml
@model MvcMovie.Models.Movie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index">
                    <button type="button" class="btn btn-dark">Back to List</button>
                </a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovie/Views/Movies/Delete.cshtml
@model MvcMovie.Models.Movie

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index">
            <button type="button" class="btn btn-dark">Back to List</button>
        </a>
    </form>

</div>

MvcMovie/Views/Movies/Details.cshtml
@model MvcMovie.Models.Movie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
   
    <a asp-action="Edit" type="button" asp-route-id="@Model.Id">
        <button type="button" class="btn btn-warning">Edit</button>
    </a>
<a asp-action="Index">
        <button type="button" class="btn btn-dark">Back to List</button>
    </a>
</div>

MvcMovie/Views/Movies/Edit.cshtml
@model MvcMovie.Models.Movie

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index">
                    <button type="button" class="btn btn-dark">Back to List</button>
                    </a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovie/Views/Movies/Index.cshtml
@model IEnumerable<MvcMovie.Models.Movie>


@{ ViewData["Title"] = "COVID";
    var covid = ViewData["covid"] as MvcMovie.Models.Movie;
    var covidList = ViewData["covidList"] as List<MvcMovie.Models.Movie>;
    }

<div class="card">
    <table class="table">
        <thead>

        </thead>
        <thead class="table-info">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReleaseDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Genre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    <form action="/Movies/index">
                        <div class="row">
                            <div class="col-md-6"></div>
                            <div class="col-md-4">
                                <input class="form-control " name="titleName" type="search" placeholder="Search" aria-label="Search">
                            </div>
                            <div class="col-md-2">
                                <button class="btn btn-success" type="submit">Search</button>
                            </div>
                        </div>
                    </form>

                </th>
            </tr>



        </thead>
        <tbody>
            @foreach (var item in Model)
            {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ReleaseDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Genre)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Price)
    </td>
    <td style="text-align:right">
        <a asp-action="Details" asp-route-id="@item.Id">
            <button type="button" class="btn btn-primary">Detail</button>
        </a>
        <a asp-action="Edit" type="button" asp-route-id="@item.Id">
            <button type="button" class="btn btn-warning">Edit</button>

        </a>
        <a asp-action="Delete" asp-route-id="@item.Id">
            <button type="button" class="btn btn-danger">Delete</button>
        </a>


    </td>
</tr>
}
        </tbody>
    </table>
    </div>
<br>
<br>
    <div class="row">
        <div class="col-md-6"></div>

        <a asp-action="Create">
            <button type="button" class="btn btn-success">Create</button>
        </a>

    </div>


    <style>
    </style>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


    }


MvcMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Covid</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3" style="background-color: #e3f2fd;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Covid" asp-action="Index">Covid Today</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MvcMovie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>